### ISSUE TITLE
ModuleNotFoundError: No module named 'ReceiveConnections'

### ISSUE THREAD

**Issue by nconder** [Tapawingo/FreeTakServer#61]
[verbose.txt](https://github.com/Tapawingo/FreeTakServer/files/4808510/verbose.txt)

Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-106-generic x86_64)

I followed the new install instructions on the home page. 

Tried to starting with both commands below and received a couple different errors for each with `ModuleNotFoundError: No module named 'ReceiveConnections`

I checked `/usr/local/lib/python3.6/dist-packages/FreeTAKServer/controllers` for ReceiveConnections.py and it is their.

`#pip3 check FreeTakServer
No broken requirements found.`

`#python3 -m FreeTAKServer.controllers.Orchestrator
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/FreeTAKServer/controllers/Orchestrator.py", line 11, in <module>
    from ReceiveConnections import ReceiveConnections
ModuleNotFoundError: No module named 'ReceiveConnections'
`
and 

`#python3 -m FreeTAKServer.controllers.Orchestrator -CoTPort 8099 -CoTIP 192.168.2.65 -DataPort 9999
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/FreeTAKServer/controllers/Orchestrator.py", line 11, in <module>
    from ReceiveConnections import ReceiveConnections
ModuleNotFoundError: No module named 'ReceiveConnections'
`

**Comment by brothercorvo** [comment]
fixed in 0.8.20
